kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: greeting-console
spec:
  nodeSelector: {}
  strategy:
    type: Docker
  source:
    type: Git
    git:
      uri: 'https://github.com/JoanneYang/do400-greeting-console'
      ref: main
  output:
    to:
      kind: DockerImage
      name: quay.io/joanneyang/greeting-console
    pushSecret:
      name: lpmk/5+cEZXC09oGqm+r5aaB4Wgu5uR7yA2+pXTJFngrsFKoPlUFpqIgGsys/HMj
